// BASE DE DATOS DE CANCIONES
const keySongsList = [
    [`qhVTxAsM-Zk`,`La partida de la gitana - Airbag`],
    [`qRHZJFAk3dI`,`Violeta - Alcides`],
    [`6ETjoIj5gdE`,`Después de ti - Alejandro Lerner`],
    [`Rk3Sq3O-2e0`,`Volver a empezar - Alejandro Lerner`],
    [`U7VqtfwTcp8`,`Secretos - Alejandro Lerner`],
    [`r1g5PoRSp1c`,`Todo a pulmón - Alejandro Lerner`],
    [`Mg_yrCGCDDY`,`Dentro mío - Alejandro Lerner`],
    [`awajuiclMKY`,`No hace falta que lo digas - Alejandro Lerner`],
    [`27aiOEQyYVY`,`Algo en mi tu corazón - Alejandro Lerner`],
    [`82EdyN6bNWM`,`Juntos para siempre - Alejandro Lerner`],
    [`tii4c5GElck`,`Amarte así - Alejandro Lerner`],
    [`ZMUqIoDtSwc`,`Corazón partío - Alejandro Sanz`],
    [`44Qh0p9xE6o`,`Amiga mía - Alejandro Sanz`],
    [`lo3G6GYB9Zs`,`Mi soledad y yo - Alejandro Sanz`],
    [`A-fgpP6fOEA`,`Y ¿Si Fuera Ella? - Alejandro Sanz`],
    [`bfa1BtwFows`,`Cuando nadie me ve - Alejandro Sanz`],
    [`UNq4OazmW8s`,`Quisiera ser - Alejandro Sanz`],
    [`xNgTMDRoa60`,`No es lo mismo - Alejandro Sanz`],
    [`K8CS9v6Fa9g`,`La fuerza del corazón - Alejandro Sanz`],
    [`vF79vKAGY7U`,`Sin miedo a nada - Alex Ubago`],
    [`3mZ2zyxEUDo`,`Qué pides tu? - Alex Ubago`],
    [`khYALqZ3FhA`,`Pizza conmigo - Alfredo Casero`],
    [`33bSMJF-SfE`,`Muchacha (Ojos de papel) - Almendra`],
    [`mtI7-3ULSC0`,`Rutas argentinas - Almendra`],
    [`X48mxG8N6CM`,`Yo tomo licor - Amar Azul`],
    [`X48mxG8N6CM`,`Yo me enamore - Amar Azul`],
    [`dGgyrPahAdE`,`El polvito del amor - Amar Azul`],
    [`PQ11fWF2adg`,`Te Vas - Américo`],
    [`OYa8hL99r5w`,`Me haces tanto bien - Amistades Peligrosas`],
    [`rjd3vn9j0YI`,`Vivo por ella - Andrea Bocelli / Marta Sánchez`],
    [`7XpUKaW0NUs`,`Bonita - Andrés Cabas`],
    [`UCF9oHXhDMU`,`Flaca - Andrés Calamaro`],
    [`kQ1z3x-HxTA`,`Te quiero igual - Andrés Calamaro`],
    [`D8GP_LsGKcM`,`Loco - Andrés Calamaro`],
    [`P01hVBLP0_g`,`Crimenes perfectos - Andrés Calamaro`],
    [`3MtQosgJoZo`,`El salmón - Andrés Calamaro`],
    [`baApNWq-034`,`No se puede vivir del amor - Andrés Calamaro`],
    [`KadbC7ZGXvI`,`Cartas Sin Marcar - Andrés Calamaro`],
    [`cSd8hFz5Atk`,`Cuando te conocí - Andrés Calamaro`],
    [`BaS5Vggkxgk`,`Algún lugar encontraré - Andrés Calamaro`],
    [`hmc5sd08SRI`,`Sur - Anibal Troilo`],
    [`5ZkLJ25zGCA`,`No me faltes - Antonio Ríos`],
    [`bALVLWx_slk`,`Yo me estoy enamorando - Antonio Ríos`],
    [`VujewdKezrM`,`El fantasma - Árbol`],
    [`lqE6pwipxE4`,`Pequeños sueños - Árbol`],
    [`gFX-H8ODLb8`,`Ya lo sabemos - Árbol`],
    [`pYlvgvifhBM`,`No sé tú - Armando Manzanero`],
    [`JDJOXVBN-Rk`,`El arriero - Atahualpa Yupanqui`],
    [`wmX0N1v120A`,`Luna Tucumana - Atahualpa Yupanqui`],
    [`oblZatYQpGc`,`Arrancacorazones - Attaque 77`],
    [`GoMg-Iuetzk`,`Hacelo por mí - Attaque 77`],
    [`c1lpcz8LfG4`,`Beatle - Attaque 77`],
    [`MvuzbrIhGWI`,`Chance - Attaque 77`],
    [`eTdEmut8luM`,`Western - Attaque 77`],
    [`gra-sIV1n4U`,`David Bisbal - Ave María`],
    [`KZh60U1PqSE`,`Te voy a amar - Axel`],
    [`cMtBOR_U-pI`,`Tu amor por siempre - Axel`],
    [`VCgtSCW6DLA`,`Amo - Axel`],
    [`GNo7dqStTpM`,`Celebra la vida - Axel`],
    [`pfBIIbKJMwI`,`Afinidad - Axel`],
    [`0iwBAd5wKuI`,`Todo vuelve - Axel`],
    [`1MibkygUPLU`,`Somos Uno - Axel / Abel Pintos`],
    [`bYPLxWUagfQ`,`Ven Devórame Otra Vez - Azúcar Moreno`],
    [`LxrUkFQHYpg`,`Solo se vive una vez - Azúcar Moreno`],
    [`gqiX6YJkuK0`,`La Bomba - Azul Azul`],
    [`Kr9pab8NAJk`,`Carismático - Babasónicos`],
    [`mmjUseMccRU`,`Y qué? - Babasónicos`],
    [`9mzv9R_Dq7M`,`Irresponsables - Babasónicos`],
    [`F5-oCyBQW8k`,`Mi Primer Millón - Bacilos`],
    [`-zgDXIi1uYw`,`Caraluna - Bacilos`],
    [`b_tO-42SfjY`,`Pasos de gigante - Bacilos`],
    [`AdCCYMAiaIU`,`Guapas - Bandana`],
    [`_Snf6G9T_Yg`,`Malo - Bebe`],
    [`LyboMJ8EJtI`,`La soledad - Bersuit Vergarabat`],
    [`jXLetz8bFMQ`,`Un pacto - Bersuit Vergarabat`],
    [`dGFf1Mh5TJw`,`Yo tomo - Bersuit Vergarabat`],
    [`BHdqa4gImqU`,`Sencillamente - Bersuit Vergarabat`],
    [`SHvvarQRqvw`,`Mi caramelo - Bersuit Vergarabat`],
    [`_ncM5Sm2eVs`,`Esperando el impacto - Bersuit Vergarabat`],
    [`ACRVZzKu5h0`,`Se viene - Bersuit Vergarabat`],
    [`rHNyWyRw6Wk`,`La Argentinidad Al Palo - Bersuit Vergarabat`],
    [`MBCZ4JvDTTk`,`La bolsa - Bersuit Vergarabat`],
    [`UBNEZBX4W_0`,`Cuatro vientos - Bersuit Vergarabat`],
    [`DMz8kll-hn0`,`Olvídala - Binomio de Oro de América`],
    [`GP8AnHpibco`,`Ha Vuelto el Matador - Cacho Castaña`],
    [`TD0IkCTMDF0`,`Café la humedad - Cacho Castaña`],
    [`jaU4btMCaUo`,`Quieren matar al ladrón - Cacho Castaña`],
    [`Zq2MJ3a-_Zw`,`Cacho de Buenos Aires - Cacho Castaña`],
    [`NSmSnmDcx6s`,`Tu recuerdo - CAE`],
    [`Q9mSV1aJ9Vc`,`Como Te Extraño Mi Amor - Café Tacvba`],
    [`oHLQGmt49V4`,`Ingrata - Café Tacvba`],
    [`a6a2LhKQJ7Y`,`una nueva noche fría - Callejeros`],
    [`rDxL6AIcpeE`,`Prohibido - Callejeros`],
    [`u4opl2oVnHM`,`Colgando en Tus Manos - Carlos Baute / Marta Sánchez`],
    [`Wch9ialjAXs`,`Entre a mi pago sin golpear - Carlos Carabajal`],
    [`0tGsHECwLWY`,`El día que me quieras - Carlos Gardel`],
    [`Pb9Hv9lw5Tw`,`Mi Buenos Aires querido - Carlos Gardel`],
    [`hM8qB3l0Q7g`,`Por una cabeza - Carlos Gardel`],
    [`P0e_QCFiVzU`,`Caminito - Carlos Gardel`],
    [`0TPtsf8nSpQ`,`Volver - Carlos Gardel`],
    [`Cl9twZ6G26s`,`La Gota Fria - Carlos Vives`],
    [`pD4H6ecTiG0`,`La Bicicleta - Carlos Vives / Shakira`],
    [`Imm0ISKlhgM`,`Magia veneno - Catupecu Machu`],
    [`KoTxXXjDxk8`,`Me vuelvo cada día más loca - Celeste Carballo`],
    [`IuAwsQTA05w`,`Es la vida que me alcanza - Celeste Carballo`],
    [`AFYJ5axf02o`,`La vida es un carnaval - Celia Cruz`],
    [`pAwAtYgFQVU`,`Guantanamera - Celia Cruz`],
    [`4XmcdppjJvo`,`Conociendote - César Banana Pueyrredón`],
    [`K_EBOoc5cKM`,`La Ley y La Trampa - Chaqueño Palavecino`],
    [`45qn31c9BSU`,`Amor salvaje - Chaqueño Palavecino`],
    [`8OcKBa9QYaI`,`Fanky - Charly García`],
    [`PyiZO9CVXY0`,`De mí - Charly García`],
    [`NN_QRLgs99o`,`Chipi chipi - Charly García`],
    [`dUU4vo1UfUU`,`Buscando un símbolo de paz - Charly García`],
    [`BAuqozi64WQ`,`Los dinosaurios - Charly García`],
    [`O9UNtY89fvY`,`Me siento mucho mejor - Charly García`],
    [`jzO8x1pnbCk`,`Nos siguen pegando abajo - Charly García`],
    [`DeMCz0O7-FM`,`Demoliendo hoteles - Charly García`],
    [`swWTPkfbZxw`,`Yo No Quiero Volverme Tan Loco - Charly García`],
    [`j-T8vVXUW2k`,`No me dejan salir - Charly García`],
    [`P3L10KNMptw`,`No voy en tren - Charly García`],
    [`Z7AERldCALc`,`Hablando a Tu Corazón - Charly García / Pedro Aznar`],
    [`JctJzPSW8Xc`,`Agachadita - Charly Sosa`],
    [`dQSSWze0AwU`,`Dejaría todo - Chayanne`],
    [`em758auOncw`,`Yo te amo - Chayanne`],
    [`pAsepr0EHG4`,`Atado a tu amor - Chayanne`],
    [`dNGjCmKKl8E`,`Un sigo sin ti - Chayanne`],
    [`l_tt2i-nEDY`,`Y tu te vas - Chayanne`],
    [`qDq4jxN5HmU`,`Provocame - Chayanne`],
    [`mEnrM1YSos8`,`Torero - Chayanne`],
    [`0qXynY77ZWA`,`Salomé - Chayanne`],
    [`TIFDnE3F_Rw`,`Baila, baila - Chayanne`],
    [`yCUXzVtsYJg`,`Boom, boom - Chayanne`],
    [`_JLxVJkr-Ow`,`Procura - Chichi Peralta`],
    [`QMt7TWvY8VQ`,`Amor narcótico - Chichi Peralta`],
    [`nsX0sacEaug`,`La Ciguapa - Chichi Peralta`],
    [`9mQGd_uuFUU`,`Arrancame la vida - Chico Novarro`],
    [`uhoHr3sPjME`,`Algo contigo - Chico Novarro`],
    [`f1tmtRXyZLA`,`Mayonesa - Chocolate`],
    [`f2YwQ9AGFd8`,`Me gusta - Ciro y los Persas`],
    [`ejCjXjaDPb0`,`Mírenla - Ciro y los Persas`],
    [`xpCPIiOyvHQ`,`Vas a bailar - Ciro y los Persas`],
    [`99RtHh_tU8E`,`Como te lo digo - Commanche`],
    [`A0kPbn1851E`,`Tonta - Commanche`],
    [`udBLU0Y_G2s`,`Nada fue un error - Coti`],
    [`Fbi8_1H-kRE`,`Antes que ver el sol - Coti`],
    [`Zocpq2DWols`,`Azul - Cristian Castro`],
    [`flB_6h25_XQ`,`Lloviendo estrellas - Cristian Castro`],
    [`td2K3taR3bc`,`Lloran las rosas - Cristian Castro`],
    [`yZ8mJgcsbw8`,`No podrás - Cristian Castro`],
    [`n00wKoRcdUw`,`Ángel - Cristian Castro`],
    [`nareJpnz2Lw`,`Amor - Cristian Castro`],
    [`kEJ7apKyamc`,`La Sachapera - Cuti y Roberto Carabajal`],
    [`iA4WVngySKU`,`Deja que me vaya - Cuti y Roberto Carabajal`],
    [`WYKVuvzCpO0`,`Tratame Suavemente - Daniel Melero`],
    [`8Cu3xqnCNek`,`Zamba para Olvidarte - Daniel Toro`],
    [`-huw1RuRvTo`,`Batida de Coco - Derek López`],
    [`Nb1VOQRs-Vs`,`Color esperanza - Diego Torres`],
    [`KQABHXhMsvw`,`Qué será - Diego Torres`],
    [`ImX1AalXJbc`,`Abriendo caminos - Diego Torres`],
    [`O8TXo-BE1kg`,`Usted - Diego Torres`],
    [`ML9QIhUE5Vc`,`Tratar de estar mejor - Diego Torres`],
    [`lTTZ8PkQ_Pk`,`Penelope - Diego Torres`],
    [`--B-nPlOXk0`,`Se Que Ya No Volveras - Diego Torres`],
    [`OtxsRzIE5WA`,`Que no me pierda - Diego Torres`],
    [`Esx18epyPL0`,`Sueños - Diego Torres`],
    [`X38mOHN28bY`,`Estamos juntos - Diego Torres`],
    [`cdzpf_T2qaA`,`Spaguetti del rock - Divididos`],
    [`CJkgBc2S5oY`,`¿Qué ves? - Divididos`],
    [`pMSCKIuoFaY`,`¿Qué tal? - Divididos`],
    [`tSqdUz-tNe4`,`El 38 - Divididos`],
    [`pgmCq3vMTRA`,`Ala delta - Divididos`],
    [`wCBu0PkoNPs`,`La quiero a morir - DLG`],
    [`dS0EzSi31vk`,`Tiritando - Donald`],
    [`e5-pnDc5GlI`,`Sin ti - Donato y Estéfano`],
    [`IgFXBPK151A`,`Estoy enamorado - Donato y Estéfano`],
    [`PSCrLsr98yU`,`La Flor Azul - Dúo Coplanacu`],
    [`A8cG3M1yMlA`,`La sila del sol - El Símbolo`],
    [`pFJvw5Anb2w`,`Levantando las manos - El Símbolo`],
    [`w3atSoAHQVc`,`1, 2, 3 - El Símbolo`],
    [`qSzoj1mEz0s`,`No te preocupes - El Símbolo`],
    [`mg9g9EKei4s`,`Pa'delante Pa'tras (De Reversa) - El Símbolo`],
    [`KoT_mO7gxsY`,`Ni siquiera entre tus brazos - Ella es tan cargosa`],
    [`5muolx9ynPA`,`En redondel - Ella es tan cargosa`],
    [`WPiEbYSF9kE`,`Suavemente - Elvis Crespo`],
    [`Co0Ek9UpBnI`,`Timidez - Emanuel Ortega`],
    [`bTfLoS9i6u8`,`Toda la vida - Emmanuel`],
    [`a3Tp48ax9dY`,`Radios - Emmanuel Horvilleur`],
    [`_D9rRrBtLHU`,`Lamento boliviano - Enanitos Verdes`],
    [`Si5eQGz6fkE`,`La cárcel - Enanitos Verdes`],
    [`8HYblvYLyoo`,`Igual Que Ayer - Enanitos Verdes`],
    [`CpqMpNtvTZk`,`Cambalache - Enrique Santos Discepolo`],
    [`5TBHeVx1PjM`,`Yira yira - Enrique Santos Discepolo`],
    [`ofIFyn7E6KI`,`Cosas De La Vida - Eros Ramazzotti`],
    [`7K8q9Xh_aJw`,`Ella dijo - Estelares`],
    [`FYryPZPh5UI`,`Un dia perfecto - Estelares`],
    [`pMoENrA6Crc`,`Aire - Estelares`],
    [`9ObRKPwBf7s`,`Es el amor - Estelares`],
    [`K4BhmiNhV_8`,`Tu Calorro - Estopa`],
    [`g8-IgReC-nE`,`Amanece en la ruta - Fabiana Cantilo`],
    [`v3tAfDr0mzA`,`Mary Poppins y el deshollinador - Fabiana Cantilo`],
    [`0JnuIaYP6DI`,`Azúcar amargo - Fey`],
    [`3Ji08Heymh8`,`El colesterol - Fito Olivares`],
    [`xJCMt00NQ1Q`,`Mariposa tecknicolor - Fito Páez`],
    [`dJIX9tl0WjE`,`11 y 6 - Fito Páez`],
    [`wFCpNO0o638`,`El amor después del amor - Fito Páez`],
    [`-e7amkoFCTA`,`Fue amor - Fito Páez`],
    [`QlWvuc0ALbg`,`Al lado del camino - Fito Páez`],
    [`1DYUNaJ_rfU`,`A rodar mi vida - Fito Páez`],
    [`bttHpp2a6WA`,`Tema de Piluso - Fito Páez`],
    [`9_fqxUfKZQc`,`Polaroid de la locura ordinaria - Fito Páez`],
    [`PjrYmvtZ2PY`,`Y dale alegría a mi corazón - Fito Páez`],
    [`1WN-NIZMR3o`,`Dos en la ciudad - Fito Páez`],
    [`ROSqv1xzHqE`,`Brillante sobre el mic - Fito Páez`],
    [`SF9GkLS-si4`,`Dar es dar - Fito Páez`],
    [`SVujXH57q-I`,`Llueve Sobre Mojado - Fito Páez / Joaquín Sabina`],
    [`RDkeRUNtFQY`,`Te mando flores - Fonseca`],
    [`aGFUUsZOvNs`,`Te Amo - Franco De Vita`],
    [`w34xKj1nNZw`,`Solo importas tú - Franco De Vita`],
    [`g4oy5CB28Ds`,`Meneaito - Gaby`],
    [`aHFAXW840uM`,`Mi Historia Entre Tus Dedos - Gianluca Grignani`],
    [`8iUkmnLc1ec`,`No me Arrepiento de este Amor - Gilda`],
    [`BAuwMLmDrfA`,`Paisaje - Gilda`],
    [`mm_SwD5PYvY`,`Fuiste - Gilda`],
    [`8YBiqHBb5Ug`,`Se me ha perdido - Gilda`],
    [`yykYZhD4Wwc`,`Corazón valiente - Gilda`],
    [`WWAWQmhqWGo`,`Mi tierra - Gloria Estefan`],
    [`f1B525nIPeA`,`Oye - Gloria Estefan`],
    [`p38kvMmRpj0`,`No podré olvidarme - Grupo Red`],
    [`AErFRyzHB2k`,`Reyes de la noche - Guasones`],
    [`PAmWdwJVQQY`,`Crimen - Gustavo Cerati`],
    [`Kpl8JowH-PA`,`Adiós - Gustavo Cerati`],
    [`eAO7CEcCD3s`,`Puente - Gustavo Cerati`],
    [`ipVoFDxQofU`,`Lago en el cielo - Gustavo Cerati`],
    [`MkBSuZGHP5g`,`Soy Mi Soberano - Gustavo Cordera`],
    [`JSZn3Ouvcm8`,`La bomba loca - Gustavo Cordera`],
    [`bdqvUwn1tbE`,`Nunca quise - Intoxicados`],
    [`_aAd2EIT9d0`,`Está saliendo el sol - Intoxicados`],
    [`N6HjwkmJXlI`,`Amándote - Jaime Roos`],
    [`mIRa63YNBTE`,`Se parece mas a ti - Jambao`],
    [`Vsx8ZaSR5lg`,`La Flaca - Jarabe de Palo`],
    [`dwjq3YSlyBE`,`Depende - Jarabe de Palo`],
    [`PODFtU_HoeY`,`Tranquila - Javier García`],
    [`RKbh1tlJCx4`,`Esos Locos Bajitos - Joan Manuel Serrat`],
    [`OLAvYqiOKLA`,`Y nos dieron las diez - Joaquín Sabina`],
    [`pGlTuhfDJTA`,`Dieguitos y Mafaldas - Joaquín Sabina`],
    [`qahBeZB1g54`,`19 días y 500 noches - Joaquín Sabina`],
    [`dM0uo6644rs`,`Peor para el sol - Joaquín Sabina`],
    [`9CT0cJNN7MM`,`El Baile De La Botella - Joe Luciano`],
    [`0SM-Sz-3etI`,`Vuelve Primavera - Johnny Tedesco`],
    [`xaR1dTOuJGI`,`Estás Para Ganar - Johny Tolengo`],
    [`peGTNefNPyk`,`Zamba de mi esperanza - Jorge Cafrune`],
    [`oLSQYxJ68jI`,`Virgen india - Jorge Cafrune y Marito`],
    [`gCF66OIRPFk`,`Me haces bien - Jorge Drexler`],
    [`kdwyQP-ctZM`,`El Rey - José Alfredo Jiménez`],
    [`jCKCbTLtHHI`,`Diosito Santo - José Luis (Puma) Rodríguez`],
    [`IOk3u1moad8`,`La moza - José Luis (Puma) Rodríguez`],
    [`sshUhGUBq4w`,`Porque Te Vas - Jose Luis Perales`],
    [`f9sGyvLfQk4`,`¿Y cómo es él? - Jose Luis Perales Oficial`],
    [`9-dNwizRGPE`,`Descontrolado - Jovenes Pordioseros`],
    [`CGTOT2VezC8`,`Era En Abril - Juan Carlos Baglietto`],
    [`I_Q99x_4XfY`,`La vida es una moneda - Juan Carlos Baglietto`],
    [`34u7EJHDzOA`,`La Bilirrubina - Juan Luis Guerra`],
    [`GHV845vKeTQ`,`Burbujas de Amor - Juan Luis Guerra`],
    [`NqDsABSh5sE`,`Volverte a ver - Juanes`],
    [`7M0W6OuZhng`,`Me enamora - Juanes`],
    [`Dp9oSi9IpZ8`,`La Camisa Negra - Juanes`],
    [`dXJ_yx6BICs`,`A Dios le pido - Juanes`],
    [`y8rBC6GCUjg`,`Me Voy - Julieta Venegas`],
    [`IJ92gmhvZpM`,`Limón y sal - Julieta Venegas`],
    [`yFVbSQdJYBg`,`Eres para mí - Julieta Venegas`],
    [`CuTx1QwLPjM`,`Lento - Julieta Venegas`],
    [`-vMlpHnrsIw`,`Todo cambia - Julio Numhauser`],
    [`vRQIxDWSPss`,`El mono relojero - Kapanga`],
    [`0Mo4XMzaHYE`,`Me mata - Kapanga`],
    [`aGruFTDEIo0`,`Mamá yo quiero - King África`],
    [`t_sAFW3jwBU`,`Porque te amo - La Cumbia`],
    [`I8cnKNB2WIk`,`Hacer un puente - La Franela`],
    [`qlZGT0se3Zk`,`Fue tan bueno - La Franela`],
    [`HopCl_p95qc`,`El Extraño del Pelo Largo - La Joven Guardia`],
    [`nTGH0Hgc7_A`,`Aquí - La ley`],
    [`d1dcXgGQT2M`,`Mentira - La ley`],
    [`-8vxXsfbxj4`,`Arde la ciudad - La Mancha de Rolando`],
    [`AU1vKyeikyY`,`Calavera - La Mancha de Rolando`],
    [`uNwqI3tZS-M`,`Donde vamos - La Mancha de Rolando`],
    [`holE9qakwNA`,`Blues del equipaje - La Mississippi`],
    [`RS_puBRoRAk`,`Bum, bum - La Mona Jiménez`],
    [`Xv2vXP7R-KI`,`Beso a beso - La Mona Jiménez`],
    [`myW8YuosTq4`,`Para No Verte Más - La Mosca Tse Tse`],
    [`SR1VHK7uDYE`,`Todos Tenemos Un Amor - La Mosca Tse Tse`],
    [`VPFGUJOdaTQ`,`Te quiero comer la boca - La Mosca Tse Tse`],
    [`1RmsuZyiL0k`,`Yo te quiero dar - La Mosca Tse Tse`],
    [`EDLz0zarJUk`,`Baila Para Mí - La Mosca Tse Tse`],
    [`u3ho6cPlKNs`,`Iluminará - La Nueva Luna`],
    [`eIE_qwIiMTE`,`Y ahora te vas - La Nueva Luna`],
    [`RM4uQQ807m0`,`Te vas a arrepentir - La Nueva Luna`],
    [`nYnLVWXmRm8`,`Rosas - La Oreja de Van Gogh`],
    [`dedq0zeaIvw`,`Selva - La Portuaria`],
    [`fem9s_8TXME`,`Un Dia Cualquiera (El Bar De La Calle Rodney) - La Portuaria`],
    [`iHqIdpfaMxU`,`Nada es igual - La Portuaria`],
    [`VC5NaNsR7-8`,`Balada del diablo y la muerte - La Renga`],
    [`_FTW5MdKw98`,`El revelde - La Renga`],
    [`Ffd4mxYicbs`,`El final es en donde partí - La Renga`],
    [`iu1B3arKO1w`,`Veneno - La Renga`],
    [`w5KfuMNFAxU`,`Cuando estés acá - La Renga`],
    [`FhloTzL4mh8`,`La Locura Automática - La Secta`],
    [`IBb1sbTEy7Q`,`Traición A La Mexicana - La Zimbabwe`],
    [`HOd2M1O7B_E`,`Loco de Atar - La Zimbabwe`],
    [`5llcBScGuAE`,`Asereje - Las Ketchup`],
    [`LWd57JJRrFk`,`Personalmente - Las Pelotas`],
    [`GPeiU6RqIjA`,`Será - Las Pelotas`],
    [`_6uwlzPYcj8`,`Victimas del cielo - Las Pelotas`],
    [`DIZFmH0yVsM`,`El muerto se fue de rumba - Las Sabrosas Zarigüellas`],
    [`Cbx60pTEjdU`,`Morrissey - Leo García`],
    [`6JzGEqg-S40`,`Después de ti - Leo Mattioli`],
    [`fwu_7KBQ-c8`,`Los salieris de Charly - León Gieco`],
    [`UdEIMVbGUI4`,`Solo le pido a Dios - León Gieco`],
    [`prWudzdkQkA`,`El ángel de la bicicleta - León Gieco`],
    [`M0aAL-TncgA`,`En el país de la libertad - León Gieco`],
    [`W4J1vxdz2j8`,`Ojo Con Los Orozco - León Gieco`],
    [`TxJB9464csk`,`Pensar en nada - León Gieco`],
    [`prWudzdkQkA`,`El fantasma de Canterville - León Gieco`],
    [`CN0iPFnP4fg`,`O Quizá Simplemente Le Regale Una Rosa - Leonardo Favio`],
    [`DI-E6wYWDkU`,`La Güera Salomé - Lía Crucet`],
    [`CrLFnczA2TU`,`Qué bello - Lía Crucet`],
    [`xjSqGms0b9c`,`Solo se trata de vivir - Litto Nebbia`],
    [`O4uBSbkxoik`,`Mil horas - Los abuelos de la nada`],
    [`Rj8zXVQ3j18`,`Lunes por la madrugada - Los abuelos de la nada`],
    [`IoHGvc7kcK4`,`Sin gamulán - Los abuelos de la nada`],
    [`kN9DCWgEfG4`,`Chalamán - Los abuelos de la nada`],
    [`nxXvOEPsE0s`,`Cómo Te Voy A Olvidar - Los Ángeles Azules`],
    [`pHPTDX_vS-4`,`Loco (Tu forma de ser) - Los Auténticos Decadentes`],
    [`qFaqgPELCh0`,`No me importa el dinero - Los Auténticos Decadentes`],
    [`EuboDNGogak`,`Golpes en el corazón - Los Auténticos Decadentes`],
    [`WKM5jRAUgvU`,`Un osito de peluche de Taiwán - Los Auténticos Decadentes`],
    [`ID-iJOw9rLo`,`La guitarra - Los Auténticos Decadentes`],
    [`Qso7QJUCZyI`,`Corazón - Los Auténticos Decadentes`],
    [`_VMc6PWpm04`,`El pájaro vio el cielo y se voló - Los Auténticos Decadentes`],
    [`7oAfpgITApw`,`Vení Raquel - Los Auténticos Decadentes`],
    [`x-qDdaplq8c`,`Besándote - Los Auténticos Decadentes`],
    [`DrKSrwTv69Y`,`La Marca de la Gorra - Los Auténticos Decadentes`],
    [`EQpcMXBprMc`,`Como Me Voy a Olvidar - Los Auténticos Decadentes`],
    [`iuFdjf0S-UA`,`Diosa - Los Auténticos Decadentes`],
    [`iw2EnH0hhSU`,`Los piratas - Los Auténticos Decadentes`],
    [`1diUFAck7V8`,`Siga El Baile - Los Auténticos Decadentes`],
    [`7T4xwt1d70Y`,`El murguero - Los Auténticos Decadentes`],
    [`e8CeGNGQEko`,`Kanishka - Los Brujos`],
    [`3NvM3OyXMWo`,`Avanti morocha - Los Caballeros de la Quema`],
    [`WkTr3rblADU`,`Sapo de otro pozo - Los Caballeros de la Quema`],
    [`ElbrZy8vNi8`,`Fulanos de nadie - Los Caballeros de la Quema`],
    [`ObwC5NWHCUI`,`Oxidado - Los Caballeros de la Quema`],
    [`mwty9NqTtSc`,`Tus ojos - Los Cafres`],
    [`YQ84ppyf1Z4`,`Bastará - Los Cafres`],
    [`O9OaDC97W1o`,`Aire - Los Cafres`],
    [`2k4f5fEFuIs`,`Si el amor se cae - Los Cafres`],
    [`EqGPEP6YG0k`,`Mostrame como sos - Los Cafres`],
    [`JoDG2dP89e8`,`Te sigo - Los Calzones`],
    [`BWGNmc52OmU`,`Vete de mi lado - Los Chakales`],
    [`aDNbehlq7Rg`,`Amores como el nuestro - Los Charros`],
    [`YWl5kersybU`,`Me Quedo Contigo - Los Chunguitos`],
    [`EdZSg8lJav0`,`Jurabas tú - Los del Fuego`],
    [`9taH1AsZzUY`,`Macarena - Los del Río`],
    [`ouKJEuk73T4`,`El baile del pimpollo - Los Delfines`],
    [`8Zdhan166z0`,`Vasos Vacíos - Los Fabulosos Cadillacs`],
    [`cl5HbmhEUBM`,`Siguiendo la luna - Los Fabulosos Cadillacs`],
    [`pjPA7CXutDw`,`El matador - Los Fabulosos Cadillacs`],
    [`9xua8KKPZME`,`Mal bicho - Los Fabulosos Cadillacs`],
    [`VOXeTeQKS2c`,`Manuel Santillán, el León - Los Fabulosos Cadillacs`],
    [`fh8JrvfUDvw`,`Padre nuestro - Los Fabulosos Cadillacs`],
    [`Pev2i1f1DWg`,`Calaveras y diablitos - Los Fabulosos Cadillacs`],
    [`2aPg64D5Eew`,`Yo te avisé - Los Fabulosos Cadillacs`],
    [`ApMVfI_55j8`,`La parte de adelante - Los Fabulosos Cadillacs`],
    [`sJPQnlr_mJw`,`Muchacha triste - Los Fantasmas del Caribe`],
    [`FN8dMe3ME7M`,`Bicho, bicho - Los Fatales`],
    [`ABQmiJ9b4No`,`Comadre Compadre - Los Fatales`],
    [`gLOzJ0SSGSA`,`La balsa - Los Gatos`],
    [`Z3n_q_2vdek`,`Chacarera del Rancho - Los hermanos Ábalos`],
    [`ku9374-DdwM`,`La rubia en el avión - Los Ladrones Sueltos`],
    [`N8atWR10c6g`,`No le dijo nada - Los Ladrones Sueltos`],
    [`DQ7gm6bBJJQ`,`Canción de despedida - Los Lunes`],
    [`seWZ2OTTl84`,`Él soy yo - Los Mensajeros del Amor`],
    [`KeopnkizoV4`,`Por Eso Vivo - Los Moykanos`],
    [`uf0j5mPHgVg`,`Otra Vez en la Vía - Los Náufragos`],
    [`jgWabrr6wUk`,`De Boliche en Boliche - Los Náufragos`],
    [`y35rTgAz-UM`,`Zapatos Rotos - Los Náufragos`],
    [`ycnKIM0M-nM`,`Yo en Mi Casa y Ella en el Bar - Los Náufragos`],
    [`tMgoCRyKx2g`,`Entre la tierra y el cielo - Los Nocheros`],
    [`TMBL4KlX9t8`,`La Yapa - Los Nocheros`],
    [`0enHNpgmt6o`,`No Saber De Ti - Los Nocheros`],
    [`FVJgWBMzqME`,`El bombón - Los Palmeras`],
    [`pGjWccgKUgk`,`Soy Sabalero - Los Palmeras`],
    [`8VThm5QvP1M`,`Perfidia - Los Panchos`],
    [`zPxlLzbFpMg`,`Pupilas lejanas - Los Pericos`],
    [`O2dfgfSJXWA`,`Runaway - Los Pericos`],
    [`Ink1bz7f5UQ`,`Waitin' - Los Pericos`],
    [`qCccnjB4plQ`,`Párate y mira - Los Pericos`],
    [`xlqN6pYG0qs`,`Mucha experiencia - Los Pericos`],
    [`rXCbSIKB9mI`,`Sin cadenas - Los Pericos`],
    [`spnzJNILQak`,`Complicado y aturdido - Los Pericos`],
    [`JOF5M0JsFJM`,`Bajo la Rambla - Los Perros`],
    [`w4Oyw9kGu5A`,`Bicho de ciudad - Los Piojos`],
    [`Yn28dEOMe0U`,`Ruleta - Los Piojos`],
    [`lZCIDNEDqM8`,`Como Alí - Los Piojos`],
    [`Jf_Ach2THWs`,`El farolito - Los Piojos`],
    [`U0tLeu-n5Ek`,`Casualidad - Los Rancheros`],
    [`BUKHMGiW_rY`,`Sin documentos - Los Rodriguez`],
    [`RJPbZo1zvDA`,`Mucho mejor - Los Rodriguez`],
    [`bKcv-D2YwP0`,`Para no olvidar - Los Rodriguez`],
    [`mG-EXl0d1jg`,`Diez años después - Los Rodriguez`],
    [`ieZ6BbJ6CBo`,`Mi enfermedad - Los Rodriguez`],
    [`boWlBD2BVik`,`Milonga del marinero y el capitán - Los Rodriguez`],
    [`87ZsJnRTWzU`,`Me estás atrapando otra vez - Los Rodriguez`],
    [`qgPiBisxP2A`,`Todavía una canción de amor - Los Rodriguez`],
    [`H2kpsYjLt8E`,`Aquí no podemos hacerlo - Los Rodriguez`],
    [`quIe1lxWByw`,`Salud (dinero y amor) - Los Rodriguez`],
    [`1jMpxdWtClY`,`Decile Que Lo Quiero - Los Sultanes`],
    [`bZ5rvxxl2aQ`,`Agente, agente - Los Sultanes`],
    [`h-HylkKKTWQ`,`Campanas en la noche - Los Tipitos`],
    [`ol-1gzSZbtU`,`Silencio - Los Tipitos`],
    [`FHYvYopdB4I`,`Brujería - Los Tipitos`],
    [`JnDFh6G7B1o`,`Fuego en Anymaná - Los trovadores`],
    [`U0EcmseuV60`,`Pensé que se trataba de cieguitos - Los Twist`],
    [`VqBUMK8RfXg`,`El estudiante - Los Twist`],
    [`VO7UNXmDDZo`,`Ricardo Ruben - Los Twist`],
    [`4pF2KbZrKG0`,`Twist de Luis - Los Twist`],
    [`cgYBsUIv8QA`,`Atrevete a Mirarme de Frente - Los Wawancó`],
    [`r9Uy9EweEEQ`,`Y así, y así - Luciano Pereyra`],
    [`tCHEmGhreDY`,`Malena - Lucio Demare`],
    [`VSWSnIcnoH4`,`Seguir viviendo sin tu amor - Luis Alberto Spinetta`],
    [`tcSIVdhbswM`,`Yo No Se Mañana - Luis Enrique`],
    [`gnpoyWNjaG4`,`Quisiera Poder Olvidarme De Ti - Luis Fonsi`],
    [`qQovTtOk6Cw`,`No me doy por vencido - Luis Fonsi`],
    [`4TIQAlXgcm4`,`Cuando calienta el sol - Luis Miguel`],
    [`QfGc8PLZgaY`,`La media vuelta - Luis Miguel`],
    [`ETVV404OzTA`,`Entregate - Luis Miguel`],
    [`oqBE5d7G2cA`,`Culpable o No (Miénteme Como Siempre) - Luis Miguel`],
    [`kCv8ipMi-BE`,`Hasta Que Me Olvides - Luis Miguel`],
    [`wOjzo02Tmck`,`La Incondicional - Luis Miguel`],
    [`pOnxY24Y5vA`,`Será que no me amas - Luis Miguel`],
    [`3IRBm9DjBdQ`,`Suave - Luis Miguel`],
    [`yG7MPEQm1-w`,`Ahora te puedes marchar - Luis Miguel`],
    [`w_hxLbcQq9M`,`Tengo Todo Excepto A Ti - Luis Miguel`],
    [`OMI2BelnlLE`,`El Oficio De Ser Mamá - Macaferri & Asociados`],
    [`6XjlkJhJ51k`,`Vuela, Vuela - Magneto`],
    [`IFxv42xPPXU`,`A Veces - Mambrú`],
    [`WJTkf0ahRtQ`,`Caribe azul - Man Ray`],
    [`idEH13MQFrQ`,`Sola en los bares - Man Ray`],
    [`7IlMVIDn140`,`Todo cambia - Man Ray`],
    [`86Ki1SMNLGs`,`Vivir sin aire - Maná`],
    [`kzMyk9AITdE`,`De Pies A Cabeza - Maná`],
    [`86Ki1SMNLGs`,`Vivir sin aire - Maná`],
    [`pKNIRQlY9a8`,`Cariposa traicionera - Maná`],
    [`i6RGhXIhwXw`,`Labios compartidos - Maná`],
    [`6ldw5Zmx1RI`,`Oye mi amor - Maná`],
    [`mfBGQykDKuQ`,`En el muelle de San Blás - Maná`],
    [`uLMqsPZGhwk`,`Se me olvidó otra vez - Maná`],
    [`4uA3S_QI9HM`,`Clavado en un bar - Maná`],
    [`b9CHW4z1g6k`,`Jugo de tomate - Manal`],
    [`rs6Y4kZ8qtw`,`Me gustas tú - Manu Chao`],
    [`TyA-oz7lSrc`,`Clandestino - Manu Chao`],
    [`ZkxntXLvqAI`,`Rescata mi corazón - Manuel Wirzt`],
    [`lI6ELv0oAE8`,`Hoy te necesito - Manuel Wirzt`],
    [`zOf3DcqZcGY`,`Donde quieras que estés - Manuel Wirzt`],
    [`kMNPv_HXffQ`,`Vivir mi vida - Marc Anthony`],
    [`YBNrYvU1ovs`,`Corazón Salvaje - Marcela Morelo`],
    [`yqvKsivX1e0`,`Te está pasando lo mismo que a mí - Marcela Morelo`],
    [`qDbR1Wcrijk`,`La fuerza del engaño - Marcela Morelo`],
    [`oE27U3Kgj34`,`Si No Te Hubieras Ido - Marco Antonio Solis`],
    [`SlQsXofcU28`,`Tu cárcel - Marco Antonio Solis`],
    [`jrOimGJFnUo`,`Uno - Mariano Mores`],
    [`rjpyul0f5cE`,`Bonita y Mentirosa - Mario Luis`],
    [`1B-5Re3zbyY`,`Loquito por ti - Mario Luis`],
    [`YcM1NB04p9g`,`Desesperada - Marta Sánchez`],
    [`Zg2CPwSeHSU`,`La última lágrima - Menphis la Blusera`],
    [`VuqLL53JRoo`,`La flor más bella - Menphis la Blusera`],
    [`poiH8sjxm9Y`,`Montón de nada - Menphis la Blusera`],
    [`j_ccy_lgfIg`,`La bifurcada - Menphis la Blusera`],
    [`ojn0_8mbD3g`,`Moscato, pizza y fainá - Menphis la Blusera`],
    [`tOWqzDQ4eMk`,`Fuego En Anymaná - Mercedes Sosa`],
    [`F_FRa9htNiw`,`Alfonsina y el mar - Mercedes Sosa (Luna - Ramírez)`],
    [`hejEjJyC7_4`,`Tirá para arriba - Miguel Mateos & Zas`],
    [`0YkKqfod4jo`,`Fantasmas - Miranda`],
    [`a3hOeU7w59o`,`Perfecta - Miranda`],
    [`fIhyOeMGQN4`,`Mentía - Miranda`],
    [`y6-H9HMb9qM`,`Yo te diré - Miranda`],
    [`SlCLHax4Y50`,`Prisionero - Miranda`],
    [`eap0G9ldKc0`,`Don - Miranda`],
    [`QOoYIZtRRn0`,`Un mundo ideal - Montaner / Michelle`],
    [`i8pdMdShHCU`,`El oso - Moris`],
    [`P3VJ3v26QEk`,`Ayer Nomás - Moris`],
    [`htIAAQsbfTM`,`Me Muero de Amor - Natalia Oreiro`],
    [`e9GCGCpYI_U`,`Tu veneno - Natalia Oreiro`],
    [`G6OYDUomYwI`,`Cambio dolor - Natalia Oreiro`],
    [`Px8TdrXxrlQ`,`Gelatina - Nietos del Futuro`],
    [`i4fwPp1NVdo`,`Un beso y una flor - Nino Bravo`],
    [`2usuXqzv6Es`,`América, América - Nino Bravo`],
    [`TQkAIx4YjSo`,`Libre - Nino Bravo`],
    [`bn6bF4j_3lc`,`Al vacío - No te va a gustar`],
    [`j7uxvgJcWqc`,`A las nueve - No te va a gustar`],
    [`NN-e-sEg6iA`,`Ese maldito momento - No te va a gustar`],
    [`ofixFLuVmgE`,`Tan lejos - No te va a gustar`],
    [`YglZ5BzPbYs`,`Chau - No te va a gustar`],
    [`TK6n3O7DgMM`,`Inundados - Os Paralamas do Sucesso`],
    [`YRuVZFj4LtU`,`¡Oh Mamá! Ella Me Ha Besado - Pablo Ruiz`],
    [`Z9As8OJ165w`,`La Felicidad - Palito Ortega`],
    [`OqxM5nsIvgU`,`Corazón Contento - Palito Ortega`],
    [`8GFWs2IDUd4`,`Yo tengo fe - Palito Ortega`],
    [`AlWP29_ygto`,`Un muchacho como yo - Palito Ortega`],
    [`9u2oPJLJuW4`,`Despeinada - Palito Ortega / Chico Novarro`],
    [`YGTlOlQFCx0`,`Cachete, pechito y ombligo - Pancho y La Sonora Colorada`],
    [`BtiXUsZW6Hs`,`Ruta 66 - Pappo's Blues`],
    [`0W4bQ2NWGzI`,`Rock and roll y fiebre - Pappo's Blues`],
    [`INICvUKDOcU`,`Desconfío - Pappo's Blues`],
    [`82oqLCiGQvA`,`Juntos a la par - Pappo's Blues`],
    [`7Cn3CNl3_KA`,`Mi vieja - Pappo's Blues`],
    [`G1R5RpsxGyE`,`El hombre suburbano - Pappo's Blues`],
    [`dGsr9ZjWPJk`,`Endulzame Los Oídos - Patricia Sosa`],
    [`9gktP23x7XA`,`Aprender a volar - Patricia Sosa`],
    [`WlFLpKaC4_c`,`Un poco de amor francés - Patricio Rey y sus redonditos de ricota`],
    [`usC1r3DVbIY`,`Un ángel para tu soledad - Patricio Rey y sus redonditos de ricota`],
    [`CnJqYsSOgfg`,`Ji Ji Ji - Patricio Rey y sus redonditos de ricota`],
    [`PAq7xAqXTxk`,`La bestia Pop - Patricio Rey y sus redonditos de ricota`],
    [`84DBTr67OnY`,`Perro dinamita - Patricio Rey y sus redonditos de ricota`],
    [`d5ajSPyzsLo`,`Lo haré por ti - Paulina Rubio`],
    [`hcphW0zsUWo`,`A primera vista - Pedro Aznar`],
    [`i5gLjXR0ICY`,`Yo Vivo en Esta Ciudad - Pedro y Pablo`],
    [`s8cF52ll4mk`,`Todas las hojas son del viento - Pescado Rabioso`],
    [`kDZX12zY3Xs`,`Sacrificio y rock and roll - Pier`],
    [`1Yp2wE2Aigo`,`Mi viejo - Piero`],
    [`WqyVbMvbE7Q`,`Olvidame y Pega la Vuelta - Pimpinela`],
    [`jCU2zCrB37k`,`El hijo de cuca - Pocho La Pantera`],
    [`_3bsI9AK8Ak`,`Un Montón De Estrellas - Polo Montañez`],
    [`W11FK2Plud0`,`Tiburón - Proyecto Uno`],
    [`OsFfjr20tm4`,`Mentirosa - Ráfaga`],
    [`by4EHmvME1c`,`Una cerveza - Ráfaga`],
    [`fIbTovslJDs`,`Agüita - Ráfaga`],
    [`LL9VcxD2Ulw`,`Una Ráfaga de Amor - Ráfaga`],
    [`GjhQqtCzRDw`,`Fiesta - Raffaella Carrà`],
    [`7GQxiyP0hhI`,`Hay Que Venir Al Sur (Tanti Auguri) - Raffaella Carrà`],
    [`UIl27cgpKaw`,`Mujer amante - Rata Blanca`],
    [`w5ODkszYleo`,`Aún estás en mis sueños - Rata Blanca`],
    [`4sliGo63vQQ`,`Rock del gato - Ratones Paranoicos`],
    [`INnFGw-6OPE`,`Ya morí - Ratones Paranoicos`],
    [`WwyYqDX5JvM`,`Sigue girando - Ratones Paranoicos`],
    [`3ER2bTi_hFA`,`Rock del pedazo - Ratones Paranoicos`],
    [`Z9eb1umT8rg`,`Para siempre - Ratones Paranoicos`],
    [`U3lDkGNU5aA`,`Vicio - Ratones Paranoicos`],
    [`mz1gnhTTLiI`,`Bailando en la vereda - Raúl Porchetto`],
    [`shuxW04gs2c`,`Señora de las Cuatro Décadas - Ricardo Arjona`],
    [`uoVD-XFO1AU`,`El Problema - Ricardo Arjona`],
    [`Y-ffY9mbZBo`,`Te conozco - Ricardo Arjona`],
    [`ekfKf8uXIYE`,`Minutos - Ricardo Arjona`],
    [`b7_D-sQ9ung`,`Dime que no - Ricardo Arjona`],
    [`Qtotvir4BqY`,`Mujeres - Ricardo Arjona`],
    [`iWlXTgjaQik`,`Volver - Ricardo Montaner`],
    [`h8giBsN_Uyk`,`Déjame Llorar - Ricardo Montaner`],
    [`ChgiRSw-oGc`,`Castillo azul - Ricardo Montaner`],
    [`x1wwMnua4N8`,`Me va a extrañar - Ricardo Montaner`],
    [`xqItObiJm-g`,`Cachita - Ricardo Montaner`],
    [`RQAXUtvTNWo`,`Tan enamorados - Ricardo Montaner`],
    [`-D7GPp6ZmWI`,`Que Tendrá El Petiso - Ricky Maravilla`],
    [`0emP6RdAZzE`,`La copa de la vida - Ricky Martin`],
    [`cpBPYcEegJo`,`Fuego contra fuego - Ricky Martin`],
    [`OZ_BGqnrlrQ`,`Nada es imposible - Ricky Martin`],
    [`tn5b4-VbULs`,`Tu recuerdo - Ricky Martin`],
    [`ctQ4zbiF97Y`,`María - Ricky Martin`],
    [`BNzysvxFObM`,`Dime Que Me Quieres - Ricky Martin`],
    [`0U3SkZEBGDY`,`Disparo al Corazón - Ricky Martin`],
    [`Ff4JCT8sUHI`,`Vuelve - Ricky Martin`],
    [`GORzuKJVeas`,`Te Extraño, Te Olvido, Te Amo - Ricky Martin`],
    [`-XBIC81dkqo`,`Pégate - Ricky Martin`],
    [`QSb703_joWE`,`Tal vez - Ricky Martin`],
    [`p47fEXGabaY`,`Livin' La Vida Loca - Ricky Martin`],
    [`PnyelXDBBnQ`,`La Mordidita - Ricky Martin`],
    [`2Wwwg7dmtm8`,`Vente pa' ca - Ricky Martin`],
    [`fL7Yx8ZY6r4`,`Sube a mi Voiture - Riff`],
    [`Aiim2deDO6w`,`La Bamba - Ritchie Valens`],
    [`XQWwO9YMpS8`,`Amigo - Roberto Carlos`],
    [`qQdEEzTeYTs`,`Naranjo en Flor - Roberto Goyeneche`],
    [`3KycUjkM2u0`,`Amor calsificado - Rodrigo`],
    [`RXs36c-PGys`,`Lo mejor del amor - Rodrigo`],
    [`7fUJRUl3s4I`,`Ocho cuarenta - Rodrigo`],
    [`WcJwAWOynEU`,`Soy cordobés - Rodrigo`],
    [`cBQTqvlZbSo`,`Como le digo - Rodrigo`],
    [`XmZqIn6BiOs`,`El talisman - Rosana`],
    [`-xr8Unx7DEM`,`A fuego lento - Rosana`],
    [`sKoK3XnTd3g`,`Si tu no estás aquí - Rosana`],
    [`C2XI-6s9ssk`,`Estoy Aqui - Rosario`],
    [`0hcoNykaI3k`,`Pedro Navaja - Ruben Blades`],
    [`_om0sPqY7bE`,`Cha Cha, Muchacha - Ruben Rada`],
    [`0vSiOg5O7PI`,`Muriendo De Plena - Ruben Rada`],
    [`qTln44P3Gow`,`Estoy Hecho un Demonio - Safari`],
    [`NeGN_cs9yfE`,`Rosa, rosa - Sandro`],
    [`NUOA3XtUS0Q`,`Porque Yo Te Amo - Sandro`],
    [`70vxLfL-xqc`,`Tengo - Sandro`],
    [`clwRbDgFqG0`,`Penumbras - Sandro`],
    [`q_BOQDKIwEM`,`Dame el fuego de tu amor - Sandro`],
    [`t6omUxqhG78`,`Corazón espinado - Santana / Maná`],
    [`3k4b7wfkqm0`,`Movidito, movidito - Sebastián`],
    [`kSt-zOzRTTY`,`Quiero Tener Tu Presencia - Seguridad Social`],
    [`ziK5_N1Psfo`,`Bailar pegados - Sergio Dalma`],
    [`3dvaH_AYqWQ`,`Te Quiero Tanto - Sergio Denis`],
    [`WJ7Vg-701t8`,`Un poco loco - Sergio Denis`],
    [`JlV1pg7Wk_o`,`Seminare - Serú Girán`],
    [`3NuCRXTZ_hs`,`No llores por mí, Argentina - Serú Girán`],
    [`kzupWpAIh10`,`Viernes, 3AM - Serú Girán`],
    [`8VDXZbxRlHQ`,`Peperina - Serú Girán`],
    [`6Tojy7dDpqQ`,`Cinema Verité - Serú Girán`],
    [`a1TGCp9DDLU`,`Eiti Leda - Serú Girán`],
    [`wTZ7A-h8yTs`,`Tú - Shakira`],
    [`SHq2qrFUlGY`,`Perro Fiel - Shakira`],
    [`GnCQj5IHILM`,`Pies descalzos, sueños blancos - Shakira`],
    [`a8Rwz6zBJSE`,`Suerte - Shakira`],
    [`GKlpL4FhzUs`,`Las de la Intuición - Shakira`],
    [`cNIJCqmUlJI`,`No creo - Shakira`],
    [`D66QEmdXg3w`,`Te Aviso, Te Anuncio - Shakira`],
    [`5BzkbSq7pww`,`Ojos así - Shakira`],
    [`B3gbisdtJnA`,`Ciega, Sordomuda - Shakira`],
    [`BPidLpADlaM`,`Día de enero - Shakira`],
    [`jgCh19FJ1hg`,`Te dejo Madrid - Shakira`],
    [`MlKFvEqXLxY`,`Si te vas - Shakira`],
    [`bE3M5mYki0A`,`Estoy aquí - Shakira`],
    [`Dsp_8Lm1eSk`,`La Tortura - Shakira / Alejandro Sanz`],
    [`AkcNqXy9yfo`,`Unicornio - Silvio Rodríguez`],
    [`JB8c9deYEfE`,`Ojalá - Silvio Rodríguez`],
    [`fSYPj6S5VG8`,`Sirena - Sin Bandera`],
    [`-hoZpSoKAYE`,`Entra en mi vida - Sin Bandera`],
    [`T_FkEw27XJ0`,`De música ligera - Soda Stereo`],
    [`UEchfRz0D8Q`,`Cuando pase el temblor - Soda Stereo`],
    [`LalPz4lIZYk`,`Persiana americana - Soda Stereo`],
    [`ko24BZXdK8c`,`Nada personal - Soda Stereo`],
    [`lGptyREttJ4`,`Prófugos - Soda Stereo`],
    [`iICWs8NBiIc`,`En la ciudad de la furia - Soda Stereo`],
    [`4rWsCoNumKw`,`A don Ata - Soledad Pastorutti`],
    [`QFqcdJqAayo`,`Que nadie sepa mi sufrir - Soledad Pastorutti`],
    [`a-28PW8o9Kw`,`Tren del cielo - Soledad Pastorutti`],
    [`dfjmR8s8eWo`,`Pega la vuelta - Sombras`],
    [`tVf7AxjSX8Q`,`La ventanita - Sombras`],
    [`kAKVT1HWNsg`,`A Puro Dolor - Son By Four`],
    [`1Zjm0uh8oeA`,`Canción para mi muerte - Sui Generis`],
    [`kA2NW3WwFDY`,`Necesito - Sui Generis`],
    [`oi1AbEfowOs`,`Aprendizaje - Sui Generis`],
    [`DrKRNJGAyHw`,`Rasguña las piedras - Sui Generis`],
    [`TumINAbkdSY`,`Confesiones de Invierno - Sui Generis`],
    [`CV26dC_acno`,`El día que apagaron la luz - Sui Generis`],
    [`QuaGBNkdTso`,`La rubia tarada - Sumo`],
    [`P7M9U0D06iI`,`Mejor no hablar de ciertas cosas - Sumo`],
    [`v-uUfI8IVyw`,`Los viejos vinagres - Sumo`],
    [`txZw4iMtgJo`,`La melodía de Dios - Tan Biónica`],
    [`V419yO6FeIU`,`Ciudad mágica - Tan Biónica`],
    [`xRaNtoiUkjQ`,`Loca - Tan Biónica`],
    [`GBdMAYE03Kc`,`Tu amor - Tango 4`],
    [`z0tvPLhwDFQ`,`Mientes - Tango 4`],
    [`j-Ov474rwuw`,`Amor A La Mexicana - Thalia`],
    [`n0L4l0PNnNo`,`Arrasando - Thalia`],
    [`EMAjgSJr4Jg`,`Piel morena - Thalia`],
    [`a6OECRJZuuo`,`Hasta Que Salga El Sol - The Orions`],
    [`kXTRHBvaaLM`,`Ya llegó la primavera - The Sacados`],
    [`T9TgfGuQUOk`,`Mas de Lo Que Te Imaginas - The sacados`],
    [`u_7OnT5wwMg`,`Se dice de mi - Tita Merello`],
    [`AwKBBaZ19SY`,`Kilómetro 11 - Tránsito Cocomarola`],
    [`rYmguNi2D_E`,`Pasos al costado - Turf`],
    [`_SKaPv4DVgE`,`Magia blanca - Turf`],
    [`71_ipsv8VNQ`,`Loco un poco - Turf`],
    [`Jc3__wMvrdo`,`No se llama amor - Turf`],
    [`hcWwpot2W5g`,`Yo no me quiero casar, y usted? - Turf`],
    [`1XXDzaMy_L8`,`El Amor Es Más Fuerte - Ulises Butrón (Tango Feroz)`],
    [`NmQpAPt3cQw`,`Me Das Cada Día Más - Valeria Lynch`],
    [`H71SUn2lOUg`,`Que ganas de no verte nunca más - Valeria Lynch`],
    [`diI65OKAKeI`,`Ámame en cámara lenta - Valeria Lynch`],
    [`3EVyraLWf_s`,`Solo un momento - Vicentico`],
    [`VDfBe5HQ8v4`,`Se despierta la ciudad - Vicentico`],
    [`21u11ive2kM`,`Los caminos de la vida - Vicentico`],
    [`idU8AzhDVXU`,`Todavía cantamos - Victor Heredia`],
    [`Gs9TnZXAS-Q`,`Me gustas mucho - Viejas Locas`],
    [`WBZlcr4SE78`,`Todo sigue igual - Viejas Locas`],
    [`1r-XsNYFhiU`,`Bye Bye (Dejame) - Vilma Palma e Vampiros`],
    [`95kf6cCasfg`,`Auto rojo - Vilma Palma e Vampiros`],
    [`bNxsYHjZAi4`,`Pachanga - Vilma Palma e Vampiros`],
    [`foM3nXxaooQ`,`El Baile del Ladrillo - Violeta Rivas`],
    [`bB9MXbgQSiw`,`Qué suerte! - Violeta Rivas`],
    [`mQNqA3WHaZE`,`Luna de miel en la mano - Virus`],
    [`FyTCNla9zwg`,`Pronta entrega - Virus`],
    [`P3cKrz1xHAY`,`Amor descartable - Virus`],
    [`am-JeYOF6bk`,`Imágenes Paganas - Virus`],
    [`ScM71vE25MM`,`Hay Que Salir del Agujero Interior - Virus`],
    [`gc4gQxhyVYk`,`Lollipop - Viuda e hijas de Roque Enroll`],
    [`oxMuxvxjmWs`,`Esa malvada - Volcán`],
    [`6yaU-WVAymE`,`Presente - Vox Dei`],
    [`CGjRMzbdlx4`,`Por lo que yo te quiero - Walter Olmos`],
    [`-BgsBtWJLnM`,`Adicto a ti - Walter Olmos`],
    [`2EzyhlXEFcA`,`Vienes y te vas - William Luna`],
    [`CpWawIJjDqg`,`Ven a bailar - Yamana`],
    [`gWE4Ip9ONVI`,`Tractor Amarillo - Zapato Veloz`],
];